export default {
  "plugins": [
    "stylelint-order",
    "stylelint-suitcss",
  ],
  "rules": {
    "at-rule-empty-line-before": [ "always", {
      except: ["blockless-after-blockless"],
    } ],
    "at-rule-no-vendor-prefix": true,
    "block-no-empty": true,
    "color-hex-length": "short",
    "color-no-invalid-hex": true,
    "comment-empty-line-before": "always",
    "comment-whitespace-inside": "always",
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-single-line-max-declarations": 1,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-url-quotes": "always",
    "media-feature-name-no-vendor-prefix": true,
    "length-zero-no-unit": true,
    "order/properties-alphabetical-order": true,
    "property-no-vendor-prefix": true,
    "rule-empty-line-before": "always-multi-line",
    "selector-no-vendor-prefix": true,
    "selector-pseudo-element-colon-notation": "double",
    "suitcss/custom-property-no-outside-root": true,
    "suitcss/root-no-standard-properties": true,
    "suitcss/selector-root-no-composition": true,
    "value-no-vendor-prefix": true,
  },
}
